# Generated by Django 6.1.1 on 2026-09-30 17:12

import hiring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='CV/Resume file (PDF or Word, max 5MB).', null=True, upload_to=hiring.models.resume_upload_path),
        ),
    ]
