# Generated by Django 6.1.1 on 2026-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_candidateprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_match_score',
            field=models.IntegerField(blank=True, help_text="AI-generated 0-100 match score against the job's requirements.", null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_screening_questions',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated safety/screening questions for the HR practical test.'),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_skills_extracted',
            field=models.JSONField(blank=True, default=list, help_text="Skills/certifications the AI found in the candidate's resume."),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated 2-sentence summary of candidate fit.'),
        ),
    ]
