# Generated by Django 6.1.1 on 2026-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_application_ai_match_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ai_skills_extracted',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ai_match_score',
            field=models.IntegerField(default=0, help_text="AI-generated 0-100 match score against the job's requirements."),
        ),
        migrations.AlterField(
            model_name='application',
            name='ai_screening_questions',
            field=models.TextField(blank=True, help_text='JSON-encoded list of 3 AI-generated safety/screening questions.'),
        ),
    ]
